### ISSUE TITLE
Switching between math and text

### ISSUE THREAD

**Issue by AaronDavidSchneider** [ddvk/rmapi-hwr#1]
Thanks for this component. I tried to interpret a few lines.
![Screenshot 2020-07-02 at 07 44 39](https://user-images.githubusercontent.com/7556347/86320784-e3d79100-bc37-11ea-9588-127773d32f97.png)

Gave me
```
Hallo, das ist ein Test.
E- -ma
tuperdenn: 4Th dr--DV, falls introp
```

I think both of these equations have been interpreted as text. How do you get the latex version?
Like this:
```
Hallo, das ist ein Test.
$E=mc^2$
Außerdem: $4\pi r^2 \mathrm{d}r = \mathrm{d}V$, falls isotrop
```

**Comment by ddvk** [comment]
welll, so far it is  either text or math, so far i don't think the api supports mixed content. you can use the `-type Math` param to tell it is math and get latex.

a workaround could be to mark the formulas in some way  (tool or color), then use different calls for the strokes for the equations.

Also, did you set the language to german with: `-lang de_DE`

**Comment by AaronDavidSchneider** [comment]
Thanks for the update! I didn't know about the language parameter and the type parameter. 
I think my handwriting is to bad for myScript. I just tried this 
`go run main.go -type Math Notebook3.zip`
![Screenshot 2020-07-02 at 09 46 40](https://user-images.githubusercontent.com/7556347/86331173-01f9bd00-bc49-11ea-8db8-f10c9251ff83.png)
and it returned just a blank line.
Thanks for the effort anyway!

**Comment by ddvk** [comment]
hm, it should work,  if you could attach the zip file, i can check why

**Comment by AaronDavidSchneider** [comment]
Sure!
[Notebook3.zip](https://github.com/ddvk/rmapi-hwr/files/4862720/Notebook3.zip)

**Comment by ddvk** [comment]
i had forgotten to mark / ignore the eraser strokes, can try it again

well, there are some errors in the formulas, but it's still some progress :>

**Comment by AaronDavidSchneider** [comment]
works now! Thanks. I suppose my handwriting is still a drawback 😆 
```
\begin{aligned}f^{n}_{acc}=\left( \dfrac {4\tau _{f}}{7B}\right) ^{1/2}R_{B}\\
R^{1}_{mr}=\left( \dfrac {r_{k}\tau _{f}}{0=1}\right) ^{1/3}R_{H}\\
R_{acc}=R^{n}_{acc}ur\left[ x\left( T_{f}/1p\right) ^{\gamma }\right] \\
f_{p}=\dfrac {4M}{\left( \Delta v+\Omega _{k}A_{H}\right) ^{3}}\\
R_{H}=r^{3}\sqrt {\dfrac {\mu }{3M\ast }}^{i}\\
\beta _{B}=\dfrac {4M}{\Delta v2}\\
1_{B}=\dfrac {R_{B}}{\Delta v}\\
\delta v=\Delta v+dR_{acc}\end{aligned}
```
